# Generated by Django 4.1.3 on 2023-07-28 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='bangazonapi.category'),
        ),
    ]
